In [22]:
import pandas as pd
import numpy as np



In [2]:
df = pd.read_csv("Auto.csv")

In [3]:
df.head()

mpg  horsepower
0  18.0         130
1  15.0         165
2  18.0         150
3  16.0         150
4  17.0         140

In [4]:
X = np.array(df.horsepower).reshape(-1,1)
X[:5]

array([[130],
       [165],
       [150],
       [150],
       [140]], dtype=int64)

In [5]:
y = np.array(df.mpg)

y[:5]

array([18., 15., 18., 16., 17.])

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [7]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

In [60]:
from sklearn.preprocessing import PolynomialFeatures

poly_features = PolynomialFeatures(degree = 5, include_bias = False)

X_poly_train = poly_features.fit_transform(X_train)
X_poly_test = poly_features.fit_transform(X_test)



model.fit(X_poly_train, y_train)


print("Coefficions:", model.coef_)
print("Interceptions:", model.intercept_)

Coefficions: [ 3.67099931e+00 -7.21169288e-02  6.07240004e-04 -2.36544467e-06
  3.49370614e-09]
Interceptions: -29.59874733732507


In [61]:
y_poly_pred = model.predict(X_poly_test)
y_poly_pred

array([31.68175838, 18.90908803, 34.26465101, 31.35911948, 26.01261911,
       29.6944332 , 14.07529786, 29.6944332 , 23.28998757, 35.91921944,
       11.93425336, 20.16270869, 15.31490828, 29.6944332 , 16.8271256 ,
       25.37553763, 23.28998757, 29.6944332 , 27.99929714, 25.37553763,
       23.28998757, 35.70494153, 31.99937015, 17.08556438, 32.3112165 ,
       24.75518998, 25.69212465, 20.79149798, 35.90251202, 29.35560605,
       15.97575706, 24.75518998, 17.583095  , 30.032093  , 15.65220779,
       32.3112165 , 16.30659701, 27.99929714, 16.30659701, 11.68799718,
       17.08556438, 29.6944332 , 30.032093  , 28.67663367, 15.78217078,
       11.68799718, 21.96449306, 31.68175838, 30.70157473, 31.35911948,
       15.45268098, 23.28998757, 24.75518998, 25.37553763, 19.41064484,
       19.774515  , 19.774515  , 21.96449306, 23.28998757, 23.28998757,
       14.57077928, 24.75518998, 18.90908803, 25.37553763, 23.28998757,
       27.66242454, 25.37553763, 31.35911948, 19.774515  , 11.23

In [62]:
from sklearn.metrics import mean_squared_error, r2_score

print("MSE:", mean_squared_error(y_poly_pred, y_test))
print("r2:", r2_score(y_test, y_poly_pred))

MSE: 17.87701491266065
r2: 0.6497490079874764
